# Generated by Django 2.1.1 on 2018-10-23 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='APIClient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('accesskey', models.CharField(max_length=32)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
    ]
